solution
mate-academy/js_advanced_calculator pull request #1187
Opened 2023-01-02 13:08 UTC by igor-kashchenko

2023-01-06 22:36 UTC, vanst1 approved these changes
Good job)

2023-01-09 09:20 UTC, alexandra-protyanova requested changes

2023-01-09 09:20 UTC, alexandra-protyanova commented on src/makeCalculator.js
> +    divide(a, b) {
is not the best name for variables

2023-01-09 09:20 UTC, alexandra-protyanova commented on src/makeCalculator.js
> +  const obj = {
```suggestion
  const calculator = {
```

2023-01-09 09:20 UTC, alexandra-protyanova commented on src/makeCalculator.js
> +    operate(callback, n) {
```suggestion
    operate(operation, value) {
```

2023-01-09 12:21 UTC, alexandra-protyanova approved these changes

2024-11-08 14:14 UTC, closed without merging