Add solution
mate-academy/js_advanced_calculator pull request #1463
Opened 2023-04-30 17:17 UTC by ruslanpashkov

2023-05-01 09:57 UTC, generatedman reviewed
good job!

2023-05-01 09:57 UTC, generatedman approved these changes

2023-05-03 08:48 UTC, naziamoff requested changes
Not bad. A couple of things left and we're good 👍

2023-05-03 08:48 UTC, naziamoff commented on src/makeCalculator.js
> +    },
you should not expect two parameters here, you can reference result from the inside of the method

2023-05-03 08:48 UTC, naziamoff commented on src/makeCalculator.js
> +    },
as well as you can change this.result right here, instead of returning the variable and reassigning this.result in operate function

2023-05-04 08:03 UTC, naziamoff approved these changes
good 👍 
But you should use `this` if you are inside the method and trying to reference the object you're currently in

2023-05-04 08:03 UTC, naziamoff commented on src/makeCalculator.js
> +    },
as you're inside the `calculator` here - you should reference its result directly from `this`
```suggestion
    add(number) {
      this.result += number;
    },
```

2023-12-12 12:53 UTC, closed without merging