Solution
mate-academy/js_advanced_calculator pull request #2054
Opened 2024-01-29 21:27 UTC by BoGoBooM

2024-01-29 21:32 UTC, Viktor-Kost requested changes

2024-01-29 21:32 UTC, Viktor-Kost commented on src/makeCalculator.js
> +  const calculator = {
you can return immediately

```suggestion
  return {
```

2024-01-29 21:32 UTC, Viktor-Kost commented on src/makeCalculator.js
> +  return calculator;
```suggestion
```

2024-01-29 21:32 UTC, Viktor-Kost commented on src/makeCalculator.js
> +  calculator.result = 0;
move inside an object like `result: 0,`

2024-01-29 21:32 UTC, Viktor-Kost commented on src/makeCalculator.js
> +      calculator.result += num;
use `this`. apply for other operations as well

```suggestion
      this.result += num;
      return this;
```

2024-01-29 21:33 UTC, Viktor-Kost requested changes
.

2024-01-30 21:04 UTC, BoGoBooM commented
I tried to fix the script as you said, but now it doesn't work and I can't understand why. Please help me to solve the problem

2024-01-31 07:12 UTC, etojeDenys requested changes

2024-01-31 07:12 UTC, etojeDenys commented on src/makeCalculator.js
> +      this.result = operation(this.result, num);
you forget to bind operation function to `this`
```suggestion
      this.result = operation.call(this, this.result, num);
```

2024-01-31 07:13 UTC, etojeDenys commented
> I tried to fix the script as you said, but now it doesn't work and I can't understand why. Please help me to solve the problem

feel free to ask for some help in the chat

2024-02-01 19:12 UTC, etojeDenys approved these changes
awesome

2025-02-17 11:55 UTC, closed without merging