Advanced calculator
mate-academy/js_advanced_calculator pull request #687
Opened 2022-06-06 13:03 UTC by vsupruniuk

2022-06-07 15:39 UTC, illiarerun requested changes
GJ, now let's work on fixes:

2022-06-07 15:39 UTC, illiarerun commented on src/makeCalculator.js
> +    operate(oparation, number) {
```suggestion
    operate(operation, number) {
```

2022-06-07 15:39 UTC, illiarerun commented on src/makeCalculator.js
> +    },
right now we can execute this code:
![image](https://user-images.githubusercontent.com/37161315/172422339-eb604420-4a13-43fb-a08d-f2b1125f98d1.png)
i guess it should work a bit other way, we should change object that we called `operate` on, operation shouldn't be dependant on exact object, you can somehow pass needed object from operate to this actual `operation`

2022-06-08 10:40 UTC, illiarerun requested changes

2022-06-08 10:40 UTC, illiarerun commented on src/makeCalculator.js
> +      calculator.result = 0;
use `this` here also, issue is still there

2022-06-08 14:22 UTC, jstmpelowycz approved these changes

2024-01-13 13:43 UTC, closed without merging