Solution makeCalculator
mate-academy/js_advanced_calculator pull request #989
Opened 2022-09-26 14:34 UTC by mykola-chernysh

2022-09-27 08:53 UTC, stanislav-topikha requested changes
Checklist 4-th
https://github.com/mate-academy/js_advanced_calculator/blob/master/checklist.md

2022-09-27 08:53 UTC, stanislav-topikha commented on src/makeCalculator.js
> +    },
```suggestion
    add: function(number) {
      this.result += number;
    },
```
fix it everywhere

2022-09-28 12:49 UTC, mykola-chernysh commented on src/makeCalculator.js
> +    },
> fix it everywhere

tests do not pass if I change

2022-09-30 13:56 UTC, stanislav-topikha commented
> Checklist 4-th https://github.com/mate-academy/js_advanced_calculator/blob/master/checklist.md

Fix 4-th point

2022-09-30 13:57 UTC, stanislav-topikha requested changes
⬆️

2022-10-02 17:14 UTC, stanislav-topikha approved these changes
GJ 👍🏻

2023-11-27 07:09 UTC, closed without merging